version: ">= 0.15.0"

formatter: "markdown document"

header-from: main.tf
footer-from: "_README_footer.md"

sections:
  hide: []
  show: []
  

  hide-all: false
  show-all: true

content: |-
  {{ .Header }}

  {{ .Requirements }}

  ## Examples

  ### Basic example

  ```hcl
  {{ include "examples/basic/main.tf" }}
  ```

  ### Advanced Example

  ```hcl
  {{ include "examples/advanced/main.tf" }}
  ```

  {{ .Providers }}
  
  {{ .Modules }}

  {{ .Inputs }}
  
  {{ .Outputs }}
  
  {{ .Resources }}

  {{ .Footer }}

output:
  file: "README.md"
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true